#! /usr/bin/env ruby

require 'action_view'
require 'action_pack'
require 'srt'

class View < ActionView::Base

  def initialize(assigns)
    paths = ['app/views']
    lookup_context = ActionView::LookupContext.new(paths)
    super(lookup_context, assigns)
  end

  def compiled_method_container
    self.class
  end

end

output_path = Pathname.new(__FILE__).join('../../public/sample.html')
@slug = '001-windows-open-application'
@srt = SRT::File.parse(File.new(Pathname.new(__FILE__).join("../../public/assets/videos/#{@slug}.srt")))

view = View
  .new(slug: @slug, srt: @srt)
  .render({
    layout: 'layouts/application',
    template: 'show',
    prefixes: 'contents'})

# require 'pry'
# binding.pry

File.open(output_path, 'wb') { |io|
  io.puts view
}
