website:
  title: 情報リテラシ
  subtitle: コンピュータ演習
root:
  alerts:
    - theme: danger
      text: '2020/07/03: このウェブサイトは現在作成中です。'
  show: 閲覧
  categories: カテゴリ一覧
content:
  list:
    show: 閲覧
    alert:
      under_construction: '2020/07/08: 現在準備中です。'
